
# Import the variables from the DVSDK so that you can find the DVSDK components
DVSDK=/home/patron/dvsdk_2_10_01_18
include $(DVSDK)/Rules.make
MVTOOL_PREFIX=
all:
	$(MVTOOL_PREFIX)gcc -c main.c -L. -lxhome -o test
